Repository Eunice0927/Postie, pull requests merged in 2025-01, with the labels that each got.

#18 SummaryApi 리팩토링 및 긴글요약 UI 변경
  PJ3T3_Postie.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PJ3T3_Postie/Core/Letter/View/AddLetterView.swift
  PJ3T3_Postie/Core/Letter/View/EditLetterView.swift
  PJ3T3_Postie/Core/Letter/View/SlowPostBoxView.swift
  PJ3T3_Postie/Core/Letter/ViewModel/AddLetterViewModel.swift
  PJ3T3_Postie/Core/Letter/ViewModel/EditLetterViewModel.swift
  PJ3T3_Postie/Core/Letter/ViewModel/SlowPostBoxViewModel.swift
  PJ3T3_Postie/Core/Letter/ViewModel/SummaryApi.swift
  PJ3T3_Postie/Core/Setting/View/FirebaseTestView.swift
  PJ3T3_Postie/Core/Setting/View/NoticeView.swift
Labels: 🔨 Refactor, ✨ Feat, 🎨 Design, 👀 리뷰 요청, 👍 Merge 진행

#12 Firebase Cloud Messaging 탑재
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/App/Appdelegate+extensions.swift
  PJ3T3_Postie/App/PJ3T3_PostieApp.swift
  PJ3T3_Postie/Core/Home/View/HomeView.swift
  PJ3T3_Postie/Manager/NotificationManager.swift
Labels: ✨ Feat, 👀 리뷰 요청

#13 이미지 Asset을 관리하는 static 한 배열을 담은 구조체 생성
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PJ3T3_Postie/Components/LoadingView.swift
  PJ3T3_Postie/Core/Setting/View/ProfileEditView.swift
  PJ3T3_Postie/Core/Setting/ViewModel/ProfileEditViewModel.swift
  PJ3T3_Postie/Manager/ImageAssetManager.swift
Labels: 🔨 Refactor, 👀 리뷰 요청

#19 Version 1.0.3 릴리즈
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PJ3T3_Postie/App/Appdelegate+extensions.swift
  PJ3T3_Postie/App/PJ3T3_PostieApp.swift
  PJ3T3_Postie/Components/LoadingView.swift
  PJ3T3_Postie/Core/Home/View/HomeView.swift
  PJ3T3_Postie/Core/Letter/View/AddLetterView.swift
  PJ3T3_Postie/Core/Letter/View/EditLetterView.swift
  PJ3T3_Postie/Core/Letter/View/SlowPostBoxView.swift
  PJ3T3_Postie/Core/Letter/ViewModel/AddLetterViewModel.swift
  PJ3T3_Postie/Core/Letter/ViewModel/EditLetterViewModel.swift
  PJ3T3_Postie/Core/Letter/ViewModel/SlowPostBoxViewModel.swift
  PJ3T3_Postie/Core/Letter/ViewModel/SummaryApi.swift
  PJ3T3_Postie/Core/Setting/View/FirebaseTestView.swift
  PJ3T3_Postie/Core/Setting/View/NoticeView.swift
  PJ3T3_Postie/Core/Setting/View/ProfileEditView.swift
  PJ3T3_Postie/Core/Setting/ViewModel/ProfileEditViewModel.swift
  PJ3T3_Postie/Manager/ImageAssetManager.swift
  PJ3T3_Postie/Manager/NotificationManager.swift
Labels: 🔨 Refactor, ✨ Feat, 👍 Merge 진행
