Repository Eunice0927/Postie, pull requests merged in 2025-02, with the labels that each got.

#21 특정 인물과 주고받은 편지 리스트에서 편지 추가 버튼을 누르면 이름을 자동입력
  PJ3T3_Postie/Core/Home/View/GroupedListLetterView.swift
  PJ3T3_Postie/Core/Home/View/HomeView.swift
  PJ3T3_Postie/Core/Letter/View/AddLetterView.swift
Labels: ✨ Feat, 👍 Merge 진행

#23 Letter View의 alert 리팩토링
  .github/trafico.yml
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/App/PJ3T3_PostieApp.swift
  PJ3T3_Postie/Core/Home/View/HomeView.swift
  PJ3T3_Postie/Core/Letter/View/AddLetterView.swift
  PJ3T3_Postie/Core/Letter/View/EditLetterView.swift
  PJ3T3_Postie/Core/Letter/View/SlowPostBoxView.swift
  PJ3T3_Postie/Core/Letter/View/UIImagePicker.swift
  PJ3T3_Postie/Core/Letter/ViewModel/AddLetterViewModel.swift
  PJ3T3_Postie/Core/Letter/ViewModel/EditLetterViewModel.swift
  PJ3T3_Postie/Core/Letter/ViewModel/SlowPostBoxViewModel.swift
  PJ3T3_Postie/Core/Root/View/ContentView.swift
  PJ3T3_Postie/Manager/AlertManager.swift
  README.md
  pull_request_template.md
Labels: 🔨 Refactor, 👍 Merge 진행

#24 맵뷰 검색 텍스트필드에서 키보드 숨기기 버튼 오작동 에러 수정
  PJ3T3_Postie/Core/Map/View/MapView.swift
Labels: 🛠️ Fix, 👍 Merge 진행

#26 Version 1.0.4 릴리즈
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/App/PJ3T3_PostieApp.swift
  PJ3T3_Postie/Core/Home/View/GroupedListLetterView.swift
  PJ3T3_Postie/Core/Home/View/HomeView.swift
  PJ3T3_Postie/Core/Letter/View/AddLetterView.swift
  PJ3T3_Postie/Core/Letter/View/EditLetterView.swift
  PJ3T3_Postie/Core/Letter/View/SlowPostBoxView.swift
  PJ3T3_Postie/Core/Letter/View/UIImagePicker.swift
  PJ3T3_Postie/Core/Letter/ViewModel/AddLetterViewModel.swift
  PJ3T3_Postie/Core/Letter/ViewModel/EditLetterViewModel.swift
  PJ3T3_Postie/Core/Letter/ViewModel/SlowPostBoxViewModel.swift
  PJ3T3_Postie/Core/Map/View/MapView.swift
  PJ3T3_Postie/Core/Root/View/ContentView.swift
  PJ3T3_Postie/Manager/AlertManager.swift
Labels: 👍 Merge 진행

#32 Remote Config 추가 및 앱 권장, 강제 업데이트 팝업 구분
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/App/PJ3T3_PostieApp.swift
  PJ3T3_Postie/Core/Root/View/ContentView.swift
  PJ3T3_Postie/Manager/AlertManager.swift
  PJ3T3_Postie/Manager/RemoteConfigManager.swift
Labels: ✨ Feat, 👍 Merge 진행

#30 한줄 요약 텍스트 필드와 키보드가 겹치는 이슈 수정
  PJ3T3_Postie/Core/Letter/View/AddLetterView.swift
  PJ3T3_Postie/Core/Letter/View/EditLetterView.swift
  PJ3T3_Postie/Core/Letter/View/SlowPostBoxView.swift
Labels: 🛠️ Fix, 👍 Merge 진행

#34 Version 1.0.5 릴리즈
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/App/PJ3T3_PostieApp.swift
  PJ3T3_Postie/Core/Letter/View/AddLetterView.swift
  PJ3T3_Postie/Core/Letter/View/EditLetterView.swift
  PJ3T3_Postie/Core/Letter/View/SlowPostBoxView.swift
  PJ3T3_Postie/Core/Letter/ViewModel/EditLetterViewModel.swift
  PJ3T3_Postie/Core/Root/View/ContentView.swift
  PJ3T3_Postie/Manager/AlertManager.swift
  PJ3T3_Postie/Manager/RemoteConfigManager.swift
Labels: 👍 Merge 진행
