Repository Eunice0927/Postie, pull requests merged in 2025-03, with the labels that each got.

#42 우체통, 우체국 카테고리 버튼 클릭시 지도 업데이트 되지 않는 버그 수정
  PJ3T3_Postie/Core/Map/View/MapView.swift
Labels: 🛠️ Fix, 👍 Merge 진행

#44 새로운 공지가 있으면 사이드 메뉴 아이콘에 뱃지 표시
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Assets.xcassets/line.horizontal.3.badge.symbolset/Contents.json
  PJ3T3_Postie/Assets.xcassets/line.horizontal.3.badge.symbolset/custom.line.3.horizontal.badge.svg
  PJ3T3_Postie/Core/Home/View/HomeView.swift
  PJ3T3_Postie/Core/Setting/View/NoticeView.swift
  PJ3T3_Postie/Core/Setting/View/ProfileEditView.swift
  PJ3T3_Postie/Core/Setting/View/SettingView.swift
  PJ3T3_Postie/Core/Setting/View/ThemeView.swift
  PJ3T3_Postie/Core/Setting/ViewModel/AlertViewModel.swift
  PJ3T3_Postie/Core/Setting/ViewModel/NoticeViewModel.swift
  PJ3T3_Postie/Extenstions/Color.swift
  PJ3T3_Postie/Manager/AuthManager.swift
  PJ3T3_Postie/Manager/RemoteConfigManager.swift
  PJ3T3_Postie/Manager/UserDefaultsManager.swift
Labels: ✨ Feat, 🎨 Design, 👍 Merge 진행

#47 다크모드 전용 앱 아이콘 추가
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/1024.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/114.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/120 1.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/120.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/128.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/136.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/152.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/167.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/180.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/192.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/40.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/58.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/60.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/76.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/80.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/87.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/Contents.json
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/postieAppIcon.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/postieAppIconNoBackground 1.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/postieAppIconNoBackground.png
Labels: 🎨 Design, 👍 Merge 진행

#46 업로드 한 이미지 저장기능 추가
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Core/Letter/View/EditLetterView.swift
  PJ3T3_Postie/Core/Letter/View/LetterDetailView.swift
  PJ3T3_Postie/Core/Letter/View/LetterImageFullScreenView.swift
  PJ3T3_Postie/Core/Letter/ViewModel/LetterImageFullScreenViewModel.swift
  PJ3T3_Postie/Manager/StorageManager.swift
Labels: ✨ Feat, ⚙️ Setting, 👀 리뷰 요청

#48 Version 1.0.7 릴리즈
  PJ3T3_Postie.xcodeproj/project.pbxproj
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/1024.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/114.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/120 1.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/120.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/128.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/136.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/152.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/167.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/180.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/192.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/40.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/58.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/60.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/76.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/80.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/87.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/Contents.json
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/postieAppIcon.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/postieAppIconNoBackground 1.png
  PJ3T3_Postie/Assets.xcassets/AppIcon.appiconset/postieAppIconNoBackground.png
  PJ3T3_Postie/Assets.xcassets/line.horizontal.3.badge.symbolset/Contents.json
  PJ3T3_Postie/Assets.xcassets/line.horizontal.3.badge.symbolset/custom.line.3.horizontal.badge.svg
  PJ3T3_Postie/Components/LoadingView.swift
  PJ3T3_Postie/Core/Home/View/HomeView.swift
  PJ3T3_Postie/Core/Letter/View/AddLetterView.swift
  PJ3T3_Postie/Core/Letter/View/EditLetterView.swift
  PJ3T3_Postie/Core/Letter/View/LetterDetailView.swift
  PJ3T3_Postie/Core/Letter/View/LetterImageFullScreenView.swift
  PJ3T3_Postie/Core/Letter/View/PageViewController.swift
  PJ3T3_Postie/Core/Letter/View/SlowPostBoxView.swift
  PJ3T3_Postie/Core/Letter/ViewModel/LetterImageFullScreenViewModel.swift
  PJ3T3_Postie/Core/Map/View/MapView.swift
  PJ3T3_Postie/Core/Root/View/ContentView.swift
  PJ3T3_Postie/Core/Setting/View/InformationView.swift
  PJ3T3_Postie/Core/Setting/View/NoticeView.swift
  PJ3T3_Postie/Core/Setting/View/ProfileEditView.swift
  PJ3T3_Postie/Core/Setting/View/SettingView.swift
  PJ3T3_Postie/Core/Setting/View/ThemeView.swift
  PJ3T3_Postie/Core/Setting/ViewModel/AlertViewModel.swift
  PJ3T3_Postie/Core/Setting/ViewModel/NoticeViewModel.swift
  PJ3T3_Postie/Extenstions/Color.swift
  PJ3T3_Postie/Manager/AuthManager.swift
  PJ3T3_Postie/Manager/RemoteConfigManager.swift
  PJ3T3_Postie/Manager/StorageManager.swift
  PJ3T3_Postie/Manager/UserDefaultsManager.swift
Labels: 🔨 Refactor, ✨ Feat, 🎨 Design, 👀 리뷰 요청, 👍 Merge 진행
